# docker-compose.yml
services:
  nginx:
    image: nginx:1.25-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    networks:
      - rinha-net
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.1" # 10% de 1 CPU
          memory: "15MB"

  api1: &api
    image: juliapp/rinha-2025-elixir-vanila:latest
    hostname: api1
    environment:
      - APP_PORT=8080
    networks:
      - rinha-net
      - payment-processor
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          cpus: "0.6" # 60% de 1 CPU
          memory: "110MB"

  api2:
    <<: *api
    hostname: api2

  redis:
    image: redis:7.2-alpine
    networks:
      - rinha-net
    command: redis-server --save "" --appendonly no
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "115MB"

networks:
  rinha-net:
    driver: bridge
  payment-processor:
    external: true
